apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-rc
  labels:
    name: mongo-rc
spec:
  replicas: 1
  selector:
    name: mongo-pod
  template:
    metadata:
      labels: 
        name: mongo-pod
    spec:
      containers:
      - name: mongo
        image: mongo:3.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
