apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels: 
    name: mongo-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    name: http
  selector:
    name: mongo-pod
