apiVersion: v1
kind: ReplicationController
metadata:
  name: back-rc
  labels:
    name: back-rc
spec:
  replicas: 1
  selector:
    name: back-pod
  template:
    metadata:
      labels: 
        name: back-pod
    spec:
      nodeSelector:
        zone: node
      containers:
      - name: back
        image: veiasai/bookstore-back:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: -Xmx256m
